### ISSUE TITLE
Error when running npx cdk bootstrap

### ISSUE THREAD

**Issue by tripleri** [aws-samples/distributed-load-testing-with-locust-on-ecs#4]
I executed **npm ci** without any issues. When I run **npx cdk bootstrap** I get the error below.

distributed-load-testing-with-locust-on-ecs\node_modules\ts-node\src\index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
bin/load_test.ts:27:1 - error TS2304: Cannot find name 'n'.

27 n;
   ~

    at createTSError (C:\Users\nbrisard\GIT\distributed-load-testing-with-locust-on-ecs\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (C:\Users\nbrisard\GIT\distributed-load-testing-with-locust-on-ecs\node_modules\ts-node\src\index.ts:517:19)
    at getOutput (C:\Users\nbrisard\GIT\distributed-load-testing-with-locust-on-ecs\node_modules\ts-node\src\index.ts:752:36)
    at Object.compile (C:\Users\nbrisard\GIT\distributed-load-testing-with-locust-on-ecs\node_modules\ts-node\src\index.ts:968:32)
    at Module.m._compile (C:\Users\nbrisard\GIT\distributed-load-testing-with-locust-on-ecs\node_modules\ts-node\src\index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\nbrisard\GIT\distributed-load-testing-with-locust-on-ecs\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

**Comment by tripleri** [comment]
@tmokmss You were correct. There was a "n;" at the end of the file. Thx for your help.
